name: MythBans
version: 2.7
main: com.myththewolf.MythBans.Startup
commands:
 mute:
     description: Mutes a player from the sever
     aliases: [silence]
 ban:
     description: Bans a player
     aliases: [b]
 tempban:
     description: Temporarily Bans a Player
     aliases: [tb,tmpban]
 kick:
     description: Kick a user from the server
     aliases: [k,throw]
 banip:
     description: Bans a IP from the server
     aliases: [bip,banip,ib,ipban]
 probate:
     description: Throws a user into probation
     aliases: [p,probation,trial,pb]
 import:
     description: Dumps your banned players to mySQL
     aliases: []
 createUI:
     description: Create a site user
     aliases: []
 pardon:
     description: Unbans a player
     aliases: [unban,ub]
 pardonIP:
     description: Unbans a IP Address
     aliases: [ubanip,pip]
 getFam:
     description: Prints users of the same IP
     aliases: [sharedip,getthefam,group,fam,family]
 kickip:
     description: Kicks all users with given IP
     aliases: [kip,ipkick]
 compare:
     description: Compares a user to another
     aliases: [diff,difference]
 reportGreif:
     description: Reports greif to all server staffing.
     aliases: [greif]
 playertime:
     description: Displays Total PlayerTime
     aliases: [playtime,pt]
 mythbans:
     description: Shows API and plugin version
     aliases: []
 closedtickets:
     description: Shows closed tickets
     aliases: [closed,cts]
 player:
     description: View info on player
     aliases: [info]
 link:
     description: Links your MC account with the discord server
     aliases: [discordlink]
 potato:
     description: Turns a player into a potato
     aliases: [pot]
 softmute:
     description: Softmutes a player
     aliases: [smute]
 mbreload:
     description: Reloads MythBans
     aliases: [reloadmb,mbr]
 clearchat: 
     description: Clears chat
     aliases: [cchat]
 socialspy:
     description: Toggles socialspy
     alaises: [ss]
 mbfix:
     description: Fixes Lang issues
     aliases: []
 xenUpdate:
     description: Set xenforo group
     aliases: []
 upgradeTables:
     description: Runs SQL table upgrade and update
     aliases: []
 dump:
     description: Dumps banned players to your JSON file.
     aliases: [export]
