name: MythBans
version: 1.0
main: com.myththewolf.MythBans.Startup
commands:
 mute:
     description: Mutes a player from the sever
     aliases: [silence]
 ban:
     description: Bans a player
     aliases: [b]
 tempban:
     description: Temporarily Bans a Player
     aliases: [tb,tmpban]
 kick:
     description: Kick a user from the server
     aliases: [k,throw]
 probate:
     description: Throws a user into probation
     aliases: [p,probation,trial,pb]