name: MythBans
version: 1.0
main: com.myththewolf.MythBans.Startup
commands:
 mute:
     description: Mutes a player from the sever
     aliases: [silence]
 ban:
     description: Bans a player
     aliases: [b]
 tempban:
     description: Temporarily Bans a Player
     aliases: [tb,tmpban]
 kick:
     description: Kick a user from the server
     aliases: [k,throw]
 banip:
     description: Bans a IP from the server
     aliases: [bip,banip,ib,ipban]
 probate:
     description: Throws a user into probation
     aliases: [p,probation,trial,pb]
 import:
     description: Dumps your banned players to mySQL
     aliases: [dump,export]
 createUI:
     description: Create a site user
     aliases: []
 pardon:
     description: Unbans a player
     aliases: [unban,ub]
 pardonIP:
     description: Unbans a IP Address
     aliases: [ubanip,pip]
 getFam:
     description: Prints users of the same IP
     aliases: [sharedip,getthefam,group,fam,family]
 kickip:
     description: Kicks all users with given IP
     aliases: [kip,ipkick]
 compare:
     description: Compares a user to another
     aliases: [diff,difference]
 reportGreif:
     description: Reports greif to all server staffing.
     aliases: [greif]
 playertime:
     description: Displays Total PlayerTime
     aliases: [playtime,pt]
 tickettp:
     description: Teleports you to point of specified ticket
     aliases: [ttp,whereisgreif]